---
- name: Install smartmontools packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_items: smartmontools_packages
  when: (smartmontools_packages is defined and smartmontools_packages)

- name: create smartd configuration file
  template: src=smartd.conf.j2 dest=/etc/smartd.conf
    owner=root group=root mode=0644
  notify: restart smartd

- name: enable smartd on system startup (default file)
  lineinfile: >
    dest=/etc/default/smartmontools
    regexp="^start_smartd="
    line="start_smartd=yes"
  notify: restart smartd

- name: pass additional options to smartd on startup (default file)
  lineinfile: >
    dest=/etc/default/smartmontools
    regexp="^smartd_opts="
    line='smartd_opts="--interval=1800"'
  notify: restart smartd

- name: enable smartd service
  service: name=smartmontools enabled=yes
